name: Docs
on:
  push:
    branches:
    - main
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd docs_site
          python -m pip install -r requirements.txt
      - name: MkDocs publish
        run: |
          cd docs_site
          mkdocs gh-deploy --force
